// Generated by gencpp from file ros_sdr/hackrf_config_srv.msg
// DO NOT EDIT!


#ifndef ROS_SDR_MESSAGE_HACKRF_CONFIG_SRV_H
#define ROS_SDR_MESSAGE_HACKRF_CONFIG_SRV_H

#include <ros/service_traits.h>


#include <ros_sdr/hackrf_config_srvRequest.h>
#include <ros_sdr/hackrf_config_srvResponse.h>


namespace ros_sdr
{

struct hackrf_config_srv
{

typedef hackrf_config_srvRequest Request;
typedef hackrf_config_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct hackrf_config_srv
} // namespace ros_sdr


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_sdr::hackrf_config_srv > {
  static const char* value()
  {
    return "8abe3cfb165ed96bd1b19e38938d04c7";
  }

  static const char* value(const ::ros_sdr::hackrf_config_srv&) { return value(); }
};

template<>
struct DataType< ::ros_sdr::hackrf_config_srv > {
  static const char* value()
  {
    return "ros_sdr/hackrf_config_srv";
  }

  static const char* value(const ::ros_sdr::hackrf_config_srv&) { return value(); }
};


// service_traits::MD5Sum< ::ros_sdr::hackrf_config_srvRequest> should match 
// service_traits::MD5Sum< ::ros_sdr::hackrf_config_srv > 
template<>
struct MD5Sum< ::ros_sdr::hackrf_config_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_sdr::hackrf_config_srv >::value();
  }
  static const char* value(const ::ros_sdr::hackrf_config_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_sdr::hackrf_config_srvRequest> should match 
// service_traits::DataType< ::ros_sdr::hackrf_config_srv > 
template<>
struct DataType< ::ros_sdr::hackrf_config_srvRequest>
{
  static const char* value()
  {
    return DataType< ::ros_sdr::hackrf_config_srv >::value();
  }
  static const char* value(const ::ros_sdr::hackrf_config_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_sdr::hackrf_config_srvResponse> should match 
// service_traits::MD5Sum< ::ros_sdr::hackrf_config_srv > 
template<>
struct MD5Sum< ::ros_sdr::hackrf_config_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_sdr::hackrf_config_srv >::value();
  }
  static const char* value(const ::ros_sdr::hackrf_config_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_sdr::hackrf_config_srvResponse> should match 
// service_traits::DataType< ::ros_sdr::hackrf_config_srv > 
template<>
struct DataType< ::ros_sdr::hackrf_config_srvResponse>
{
  static const char* value()
  {
    return DataType< ::ros_sdr::hackrf_config_srv >::value();
  }
  static const char* value(const ::ros_sdr::hackrf_config_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SDR_MESSAGE_HACKRF_CONFIG_SRV_H
