// Generated by gencpp from file ros_sdr/hackrf_config_current.msg
// DO NOT EDIT!


#ifndef ROS_SDR_MESSAGE_HACKRF_CONFIG_CURRENT_H
#define ROS_SDR_MESSAGE_HACKRF_CONFIG_CURRENT_H

#include <ros/service_traits.h>


#include <ros_sdr/hackrf_config_currentRequest.h>
#include <ros_sdr/hackrf_config_currentResponse.h>


namespace ros_sdr
{

struct hackrf_config_current
{

typedef hackrf_config_currentRequest Request;
typedef hackrf_config_currentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct hackrf_config_current
} // namespace ros_sdr


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_sdr::hackrf_config_current > {
  static const char* value()
  {
    return "22e53c6482b45d72b0680a1186e76397";
  }

  static const char* value(const ::ros_sdr::hackrf_config_current&) { return value(); }
};

template<>
struct DataType< ::ros_sdr::hackrf_config_current > {
  static const char* value()
  {
    return "ros_sdr/hackrf_config_current";
  }

  static const char* value(const ::ros_sdr::hackrf_config_current&) { return value(); }
};


// service_traits::MD5Sum< ::ros_sdr::hackrf_config_currentRequest> should match 
// service_traits::MD5Sum< ::ros_sdr::hackrf_config_current > 
template<>
struct MD5Sum< ::ros_sdr::hackrf_config_currentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_sdr::hackrf_config_current >::value();
  }
  static const char* value(const ::ros_sdr::hackrf_config_currentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_sdr::hackrf_config_currentRequest> should match 
// service_traits::DataType< ::ros_sdr::hackrf_config_current > 
template<>
struct DataType< ::ros_sdr::hackrf_config_currentRequest>
{
  static const char* value()
  {
    return DataType< ::ros_sdr::hackrf_config_current >::value();
  }
  static const char* value(const ::ros_sdr::hackrf_config_currentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_sdr::hackrf_config_currentResponse> should match 
// service_traits::MD5Sum< ::ros_sdr::hackrf_config_current > 
template<>
struct MD5Sum< ::ros_sdr::hackrf_config_currentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_sdr::hackrf_config_current >::value();
  }
  static const char* value(const ::ros_sdr::hackrf_config_currentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_sdr::hackrf_config_currentResponse> should match 
// service_traits::DataType< ::ros_sdr::hackrf_config_current > 
template<>
struct DataType< ::ros_sdr::hackrf_config_currentResponse>
{
  static const char* value()
  {
    return DataType< ::ros_sdr::hackrf_config_current >::value();
  }
  static const char* value(const ::ros_sdr::hackrf_config_currentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SDR_MESSAGE_HACKRF_CONFIG_CURRENT_H
