// Generated by gencpp from file temp_mon/temp_val.msg
// DO NOT EDIT!


#ifndef TEMP_MON_MESSAGE_TEMP_VAL_H
#define TEMP_MON_MESSAGE_TEMP_VAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace temp_mon
{
template <class ContainerAllocator>
struct temp_val_
{
  typedef temp_val_<ContainerAllocator> Type;

  temp_val_()
    : temp(0.0)  {
    }
  temp_val_(const ContainerAllocator& _alloc)
    : temp(0.0)  {
    }



   typedef double _temp_type;
  _temp_type temp;




  typedef boost::shared_ptr< ::temp_mon::temp_val_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::temp_mon::temp_val_<ContainerAllocator> const> ConstPtr;

}; // struct temp_val_

typedef ::temp_mon::temp_val_<std::allocator<void> > temp_val;

typedef boost::shared_ptr< ::temp_mon::temp_val > temp_valPtr;
typedef boost::shared_ptr< ::temp_mon::temp_val const> temp_valConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::temp_mon::temp_val_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::temp_mon::temp_val_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace temp_mon

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'temp_mon': ['/home/aanderson/catkin_ws/src/temp_mon/msg', '/home/aanderson/catkin_ws/src/temp_mon/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::temp_mon::temp_val_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::temp_mon::temp_val_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::temp_mon::temp_val_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::temp_mon::temp_val_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::temp_mon::temp_val_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::temp_mon::temp_val_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::temp_mon::temp_val_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1c666a4992d5d6108cc9173c68311b1d";
  }

  static const char* value(const ::temp_mon::temp_val_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1c666a4992d5d610ULL;
  static const uint64_t static_value2 = 0x8cc9173c68311b1dULL;
};

template<class ContainerAllocator>
struct DataType< ::temp_mon::temp_val_<ContainerAllocator> >
{
  static const char* value()
  {
    return "temp_mon/temp_val";
  }

  static const char* value(const ::temp_mon::temp_val_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::temp_mon::temp_val_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 temp\n\
";
  }

  static const char* value(const ::temp_mon::temp_val_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::temp_mon::temp_val_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.temp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct temp_val_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::temp_mon::temp_val_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::temp_mon::temp_val_<ContainerAllocator>& v)
  {
    s << indent << "temp: ";
    Printer<double>::stream(s, indent + "  ", v.temp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEMP_MON_MESSAGE_TEMP_VAL_H
