# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_sdr/hackrf_config.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class hackrf_config(genpy.Message):
  _md5sum = "5df33ff59a52574b6d910ea12bc909fe"
  _type = "ros_sdr/hackrf_config"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint64 frequency
float64 sample_rate
uint32 baseband_filter_bw_hz	
uint32 lnaGain
uint32 vgaGain
uint32 txvgaGain
int8 ampEnable
int8 antennaEnable

"""
  __slots__ = ['frequency','sample_rate','baseband_filter_bw_hz','lnaGain','vgaGain','txvgaGain','ampEnable','antennaEnable']
  _slot_types = ['uint64','float64','uint32','uint32','uint32','uint32','int8','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       frequency,sample_rate,baseband_filter_bw_hz,lnaGain,vgaGain,txvgaGain,ampEnable,antennaEnable

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(hackrf_config, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.frequency is None:
        self.frequency = 0
      if self.sample_rate is None:
        self.sample_rate = 0.
      if self.baseband_filter_bw_hz is None:
        self.baseband_filter_bw_hz = 0
      if self.lnaGain is None:
        self.lnaGain = 0
      if self.vgaGain is None:
        self.vgaGain = 0
      if self.txvgaGain is None:
        self.txvgaGain = 0
      if self.ampEnable is None:
        self.ampEnable = 0
      if self.antennaEnable is None:
        self.antennaEnable = 0
    else:
      self.frequency = 0
      self.sample_rate = 0.
      self.baseband_filter_bw_hz = 0
      self.lnaGain = 0
      self.vgaGain = 0
      self.txvgaGain = 0
      self.ampEnable = 0
      self.antennaEnable = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_Qd4I2b.pack(_x.frequency, _x.sample_rate, _x.baseband_filter_bw_hz, _x.lnaGain, _x.vgaGain, _x.txvgaGain, _x.ampEnable, _x.antennaEnable))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 34
      (_x.frequency, _x.sample_rate, _x.baseband_filter_bw_hz, _x.lnaGain, _x.vgaGain, _x.txvgaGain, _x.ampEnable, _x.antennaEnable,) = _struct_Qd4I2b.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_Qd4I2b.pack(_x.frequency, _x.sample_rate, _x.baseband_filter_bw_hz, _x.lnaGain, _x.vgaGain, _x.txvgaGain, _x.ampEnable, _x.antennaEnable))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 34
      (_x.frequency, _x.sample_rate, _x.baseband_filter_bw_hz, _x.lnaGain, _x.vgaGain, _x.txvgaGain, _x.ampEnable, _x.antennaEnable,) = _struct_Qd4I2b.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_Qd4I2b = struct.Struct("<Qd4I2b")
