# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_sdr/rtlsdr_config.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class rtlsdr_config(genpy.Message):
  _md5sum = "188b8912642464c74a1ab30117856134"
  _type = "ros_sdr/rtlsdr_config"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint32 frequency
uint32 sample_rate
int32 gain
int32 ppm_error
int8 gainmode
int8 dithering
int8 direct_sampling

"""
  __slots__ = ['frequency','sample_rate','gain','ppm_error','gainmode','dithering','direct_sampling']
  _slot_types = ['uint32','uint32','int32','int32','int8','int8','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       frequency,sample_rate,gain,ppm_error,gainmode,dithering,direct_sampling

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(rtlsdr_config, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.frequency is None:
        self.frequency = 0
      if self.sample_rate is None:
        self.sample_rate = 0
      if self.gain is None:
        self.gain = 0
      if self.ppm_error is None:
        self.ppm_error = 0
      if self.gainmode is None:
        self.gainmode = 0
      if self.dithering is None:
        self.dithering = 0
      if self.direct_sampling is None:
        self.direct_sampling = 0
    else:
      self.frequency = 0
      self.sample_rate = 0
      self.gain = 0
      self.ppm_error = 0
      self.gainmode = 0
      self.dithering = 0
      self.direct_sampling = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2I2i3b.pack(_x.frequency, _x.sample_rate, _x.gain, _x.ppm_error, _x.gainmode, _x.dithering, _x.direct_sampling))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 19
      (_x.frequency, _x.sample_rate, _x.gain, _x.ppm_error, _x.gainmode, _x.dithering, _x.direct_sampling,) = _struct_2I2i3b.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2I2i3b.pack(_x.frequency, _x.sample_rate, _x.gain, _x.ppm_error, _x.gainmode, _x.dithering, _x.direct_sampling))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 19
      (_x.frequency, _x.sample_rate, _x.gain, _x.ppm_error, _x.gainmode, _x.dithering, _x.direct_sampling,) = _struct_2I2i3b.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2I2i3b = struct.Struct("<2I2i3b")
